# Generated by Django 5.0.1 on 2024-03-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pethackapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.CharField(max_length=4),
        ),
    ]
